name: Deploy Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, staging]

    steps:
      - uses: actions/checkout@v4

      - run: |
          docker compose \
            --env-file .env.staging \
            -f docker-compose.yml \
            -f docker-compose.staging.yml \
            up -d --build
