name: Deploy Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, production]

    steps:
      - uses: actions/checkout@v4

      - run: |
          docker compose \
            --env-file /srv/voto-docker/.env.prod \
            -f docker-compose.yml \
            -f docker-compose.prod.yml \
            up -d --build
